HOST: 'localhost'
PORT: 5003
KAFKA_PORT: 5003
API_VERSION: (0.10.2.1)
FRAMES_TOPIC: "frames"
STATE_TABLE: "states"
RESULT_TABLE: "predictions"
SHEMA_NAME: "video_detection_service"
DB_PASSWORD: "1111111"
DB_USER: "postgres"
DB_NAME: "postgres"
MODEL_PATH: "model/yolov8n.pt"
